"use client";
import * as React from "react";
import { CheckCircle2, RefreshCw, UserCheck, XCircle } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/components/ui/toast";

const DAYS: Record<number,string> = { 1:"Mon",2:"Tue",3:"Wed",4:"Thu",5:"Fri",6:"Sat" };
export function SeniorLearnerProofCard() {
  const { toast } = useToast();
  const [data,setData]=React.useState<any>(null); const [selected,setSelected]=React.useState("");
  const load=React.useCallback(async()=>{try{const j=await fetch("/api/academics/timetable/learner-proofs").then(r=>r.json());if(!j.ok)throw new Error(j.error?.message||"Could not load learner proofs");setData(j.data);if(j.data.proofs?.[0])setSelected((current)=>current||j.data.proofs[0].id);}catch(e){toast({title:e instanceof Error?e.message:"Could not load learner proofs",tone:"error"});}},[toast]);
  React.useEffect(()=>{void load();},[load]);
  if(!data?.job)return <Card><CardContent className="p-4 text-sm text-navy-500">Learner personal timetable proofs appear after the first Senior Master generation.</CardContent></Card>;
  const proof=data.proofs.find((p:any)=>p.id===selected)??data.proofs[0];
  return <Card className="border-teal-200 dark:border-teal-900"><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle className="flex items-center gap-2"><UserCheck className="h-5 w-5 text-teal-600"/>Phase E · learner personal timetable proof</CardTitle><p className="mt-1 text-xs text-navy-600 dark:text-navy-300">Durable proof from the latest Master run: learner’s own Mathematics variant and exact Option A/B/C subjects.</p></div><Button size="sm" variant="secondary" onClick={load} aria-label="Refresh learner proofs"><RefreshCw className="h-4 w-4"/></Button></div></CardHeader><CardContent className="space-y-4"><div className="flex flex-wrap gap-2"><Badge tone="green">{data.job.valid} valid</Badge><Badge tone={data.job.invalid?"red":"neutral"}>{data.job.invalid} invalid</Badge><span className="text-xs text-navy-500">Run {new Date(data.job.startedAt).toLocaleString("en-KE")}</span></div>{data.proofs.length===0?<p className="text-sm text-navy-500">No Senior learners were present in this run.</p>:<><select value={proof?.id||""} onChange={e=>setSelected(e.target.value)} className="h-11 w-full rounded-xl border border-navy-200 bg-white px-3 text-sm dark:border-navy-700 dark:bg-navy-900">{data.proofs.map((p:any)=><option key={p.id} value={p.id}>{p.studentName} · {p.admissionNo} · {p.valid?"VALID":"REVIEW"}</option>)}</select>{proof&&<div className="space-y-3"><div className={`flex items-center gap-2 rounded-xl p-3 text-sm font-bold ${proof.valid?"bg-green-50 text-green-800 dark:bg-green-950/20 dark:text-green-300":"bg-red-50 text-red-800 dark:bg-red-950/20 dark:text-red-300"}`}>{proof.valid?<CheckCircle2 className="h-5 w-5"/>:<XCircle className="h-5 w-5"/>}{proof.valid?"Personal timetable proof passed":"Personal timetable needs correction"}</div>{proof.issues?.length>0&&<ul className="space-y-1 rounded-xl border border-red-200 p-3 text-xs text-red-700 dark:border-red-900 dark:text-red-300">{proof.issues.map((issue:string)=><li key={issue}>• {issue}</li>)}</ul>}<div className="overflow-x-auto rounded-xl border border-navy-200 dark:border-navy-700"><table className="w-full min-w-[560px] text-left text-xs"><thead className="bg-navy-50 dark:bg-navy-800"><tr><th className="p-2">Day</th><th className="p-2">Period</th><th className="p-2">Family</th><th className="p-2">Learner’s subject</th></tr></thead><tbody>{(proof.timetable??[]).map((row:any,index:number)=><tr key={`${row.dayOfWeek}-${row.period}-${index}`} className="border-t border-navy-100 dark:border-navy-800"><td className="p-2 font-bold">{DAYS[row.dayOfWeek]??row.dayOfWeek}</td><td className="p-2">{row.period}</td><td className="p-2">{row.family??row.kind}</td><td className="p-2 font-semibold">{row.subjectName} {row.subjectCode?`(${row.subjectCode})`:""}</td></tr>)}</tbody></table></div></div>}</>}</CardContent></Card>;
}
