"use client";
import * as React from "react";
import { AlertTriangle, CheckCircle2, Loader2, RefreshCw, ShieldCheck, XCircle } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/components/ui/toast";

export function SeniorReadinessCard({ classes }: { classes: any[] }) {
  const { toast } = useToast();
  const levels = React.useMemo(() => [...new Set(classes.map((c) => c.level).filter((l: string) => /(?:Grade|Form)\s*(?:10|11|12)/i.test(l)))].sort() as string[], [classes]);
  const [level, setLevel] = React.useState(levels[0] ?? "");
  const [report, setReport] = React.useState<any>(null);
  const [loading, setLoading] = React.useState(false);
  async function run() { if (!level) return; setLoading(true); try { const j = await fetch(`/api/academics/timetable/senior-readiness?level=${encodeURIComponent(level)}`).then((r) => r.json()); if (!j.ok) throw new Error(j.error?.message || "Readiness check failed"); setReport(j.data.report); } catch (e) { toast({ title: e instanceof Error ? e.message : "Readiness check failed", tone: "error" }); } finally { setLoading(false); } }
  if (levels.length === 0) return null;
  const Section = ({ title, rows, tone }: { title: string; rows: any[]; tone: "red"|"amber"|"green" }) => rows.length ? <div><p className={`mb-2 text-xs font-black uppercase tracking-wider ${tone === "red" ? "text-red-700 dark:text-red-300" : tone === "amber" ? "text-amber-700 dark:text-amber-300" : "text-green-700 dark:text-green-300"}`}>{title} ({rows.length})</p><div className="space-y-2">{rows.map((row) => <details key={row.code} className="rounded-xl border border-navy-200 bg-white p-3 text-sm dark:border-navy-700 dark:bg-navy-900"><summary className="cursor-pointer font-bold text-navy-900 dark:text-white">{row.title}</summary><p className="mt-1 text-navy-600 dark:text-navy-300">{row.detail}</p>{row.affectedStudentNames?.length ? <p className="mt-2 max-h-24 overflow-y-auto text-xs text-navy-500">{row.affectedStudentNames.join(" · ")}</p> : null}</details>)}</div></div> : null;
  return <Card className="border-indigo-200 dark:border-indigo-900"><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-indigo-600"/>Senior School Phase A · readiness gate</CardTitle><p className="mt-1 text-xs leading-5 text-navy-600 dark:text-navy-300">Deterministic checks only—no AI. This validates confirmed choices, three electives, pathways, Mathematics variants, teachers, 40 lessons and routine before option-block generation.</p></div><div className="flex items-center gap-2"><select value={level} onChange={(e) => { setLevel(e.target.value); setReport(null); }} className="h-9 rounded-xl border border-navy-200 bg-white px-3 text-sm dark:border-navy-700 dark:bg-navy-900">{levels.map((l) => <option key={l}>{l}</option>)}</select><Button size="sm" onClick={run} disabled={loading}>{loading ? <Loader2 className="h-4 w-4 animate-spin"/> : report ? <RefreshCw className="h-4 w-4"/> : <ShieldCheck className="h-4 w-4"/>}{report ? "Run again" : "Check readiness"}</Button></div></div></CardHeader>{report && <CardContent className="space-y-5"><div className="flex flex-wrap items-center gap-2"><Badge tone={report.ready ? "green" : "red"}>{report.ready ? "READY FOR PHASE B" : "NOT READY"}</Badge><span className="text-sm text-navy-600 dark:text-navy-300">{report.summary.students} learners · {report.summary.confirmed} confirmed · {report.summary.subjects} electives · {report.summary.classes} classes</span></div>{report.ready ? <div className="flex items-center gap-2 rounded-xl bg-green-50 p-3 text-sm font-bold text-green-800 dark:bg-green-950/20 dark:text-green-300"><CheckCircle2 className="h-5 w-5"/>All hard Phase A checks passed. Warnings still require human review.</div> : <div className="flex items-center gap-2 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-800 dark:bg-red-950/20 dark:text-red-300"><XCircle className="h-5 w-5"/>Correct every blocker before generating elective option blocks.</div>}<Section title="Blockers" rows={report.blockers} tone="red"/><Section title="Leadership review" rows={report.warnings} tone="amber"/><Section title="Passed" rows={report.passed} tone="green"/><p className="flex items-start gap-2 text-xs text-navy-500 dark:text-navy-400"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0"/>A pass does not approve the timetable. Phase B must still create three conflict-safe blocks, and the timetable committee/Head must review the final draft.</p></CardContent>}</Card>;
}
