import { NextRequest } from "next/server";
import { z } from "zod";
import { requirePermission } from "@/lib/core/session";
import { db } from "@/lib/db";
import { ok, handleError } from "@/lib/api/respond";
import { YOUTUBE_GRADE6_10_BATCH1_CANDIDATES as candidates } from "@/lib/data/youtube-grade6-10-batch1-candidates";
export const dynamic="force-dynamic"; export const maxDuration=300; const KEY="youtube_grade6_10_batch1_reviews";
type Review={status:"CANDIDATE"|"LIVE_VERIFIED"|"APPROVED_FOR_MAPPING"|"MAPPED"|"PUBLISHED"|"REJECTED"|"UNAVAILABLE";liveTitle?:string;channelTitle?:string;note?:string;checkedAt?:string;reviewedBy?:string;subjectId?:string;strandId?:string;substrandId?:string;publishedVideoId?:string};
async function readReviews():Promise<Record<string,Review>>{const row=await db.platformSetting.findUnique({where:{key:KEY}});try{return row?JSON.parse(row.value):{};}catch{return {};}}
async function saveReviews(reviews:Record<string,Review>,user:{fullName:string}){await db.platformSetting.upsert({where:{key:KEY},create:{key:KEY,value:JSON.stringify(reviews),updatedBy:user.fullName},update:{value:JSON.stringify(reviews),updatedBy:user.fullName}});}
async function liveCheck(id:string){const c=new AbortController(),timer=setTimeout(()=>c.abort(),12000);try{const url=`https://www.youtube.com/oembed?format=json&url=${encodeURIComponent(`https://www.youtube.com/watch?v=${id}`)}`;const res=await fetch(url,{signal:c.signal,headers:{"User-Agent":"NEYO-Link-Review/1.0"}});if(!res.ok)return{live:false,error:`HTTP ${res.status}`};const data=await res.json() as {title?:string;author_name?:string};return{live:true,title:data.title,channel:data.author_name};}catch(e){return{live:false,error:e instanceof Error?e.message:"Verification failed"};}finally{clearTimeout(timer);}}
export async function GET(){try{const user=await requirePermission("platform.founder_ops"),reviews=await readReviews();const[subjects,strands,substrands]=await Promise.all([db.subject.findMany({where:{tenantId:user.tenantId,archived:false},select:{id:true,name:true,code:true},orderBy:{name:"asc"}}),db.cbcStrand.findMany({where:{tenantId:user.tenantId},select:{id:true,name:true,subjectId:true},orderBy:{name:"asc"}}),db.cbcSubstrand.findMany({where:{tenantId:user.tenantId},select:{id:true,name:true,strandId:true},orderBy:{name:"asc"}})]);return ok({candidates:candidates.map(candidate=>({...candidate,review:reviews[candidate.youtubeId]??{status:"CANDIDATE"}})),subjects,strands,substrands});}catch(e){return handleError(e);}}
export async function POST(req:NextRequest){try{const user=await requirePermission("platform.founder_ops"),body=await req.json(),action=z.enum(["verify","verify_all","decide","save_mapping","publish"]).parse(body.action),reviews=await readReviews();
if(action==="verify"||action==="verify_all"){const ids=action==="verify_all"?candidates.map(c=>c.youtubeId):[z.string().parse(body.youtubeId)];for(let i=0;i<ids.length;i+=5)await Promise.all(ids.slice(i,i+5).map(async id=>{const r=await liveCheck(id);reviews[id]=r.live?{...reviews[id],status:"LIVE_VERIFIED",liveTitle:r.title,channelTitle:r.channel,checkedAt:new Date().toISOString()}:{...reviews[id],status:"UNAVAILABLE",note:r.error,checkedAt:new Date().toISOString()};}));await saveReviews(reviews,user);return ok({checked:ids.length});}
const youtubeId=z.string().parse(body.youtubeId),candidate=candidates.find(c=>c.youtubeId===youtubeId);if(!candidate)throw new Error("Candidate not found");
if(action==="save_mapping"){if(!["APPROVED_FOR_MAPPING","MAPPED"].includes(reviews[youtubeId]?.status))throw new Error("Approve the live candidate for mapping first.");const subjectId=z.string().min(1).parse(body.subjectId),strandId=z.string().min(1).parse(body.strandId),substrandId=z.string().min(1).parse(body.substrandId);const strand=await db.cbcStrand.findFirst({where:{id:strandId,tenantId:user.tenantId,subjectId}}),substrand=await db.cbcSubstrand.findFirst({where:{id:substrandId,tenantId:user.tenantId,strandId}});if(!strand||!substrand)throw new Error("Subject, strand and sub-strand must belong together.");reviews[youtubeId]={...reviews[youtubeId],status:"MAPPED",subjectId,strandId,substrandId,reviewedBy:user.fullName};await saveReviews(reviews,user);return ok({review:reviews[youtubeId]});}
if(action==="publish"){const review=reviews[youtubeId];if(review?.status!=="MAPPED"||!review.subjectId||!review.strandId||!review.substrandId)throw new Error("Complete curriculum mapping before publishing.");const video=await db.learningVideo.upsert({where:{tenantId_youtubeId:{tenantId:user.tenantId,youtubeId}},create:{tenantId:user.tenantId,youtubeId,title:review.liveTitle||candidate.title,description:`Vetted Grade ${candidate.grade.replace("Grade ","")} learning video for ${candidate.subject}.`,channelTitle:review.channelTitle||"Educational channel",thumbnailUrl:`https://img.youtube.com/vi/${youtubeId}/mqdefault.jpg`,savedById:user.id,savedByName:user.fullName,subjectId:review.subjectId,strandId:review.strandId,substrandId:review.substrandId,grade:candidate.grade,scope:"NATIONAL",approvalStatus:"APPROVED",approvedById:user.id,approvedByName:user.fullName,approvedAt:new Date()},update:{title:review.liveTitle||candidate.title,channelTitle:review.channelTitle,subjectId:review.subjectId,strandId:review.strandId,substrandId:review.substrandId,grade:candidate.grade,scope:"NATIONAL",approvalStatus:"APPROVED",approvedById:user.id,approvedByName:user.fullName,approvedAt:new Date()}});reviews[youtubeId]={...review,status:"PUBLISHED",publishedVideoId:video.id};await saveReviews(reviews,user);return ok({videoId:video.id});}
const status=z.enum(["APPROVED_FOR_MAPPING","REJECTED","CANDIDATE"]).parse(body.status);reviews[youtubeId]={...reviews[youtubeId],status,note:z.string().max(500).optional().parse(body.note),reviewedBy:user.fullName};await saveReviews(reviews,user);return ok({review:reviews[youtubeId]});}catch(e){return handleError(e);}}
