"use client";

import * as React from "react";
import { Building2, CheckCircle2, Loader2, MapPin, Pencil, Phone, Search, Trash2 } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useToast } from "@/components/ui/toast";
import { formatKES } from "@/lib/utils";

type Stage = "PLANNED"|"VISITED"|"FOLLOW_UP"|"DEMO_BOOKED"|"PILOT_PROPOSED"|"WON"|"LOST"|"NOT_NOW";
type Visit = { id:string; schoolName:string; county:string|null; town:string|null; locationNotes:string|null; schoolType:string|null; estimatedLearners:number|null; contactName:string|null; contactRole:string|null; contactPhone:string|null; contactEmail:string|null; stage:Stage; visitAt:string|null; meetingAt:string|null; followUpAt:string|null; outcome:string|null; painPoints:string|null; interestedModules:string|null; objections:string|null; currentSystem:string|null; budgetNotes:string|null; decisionProcess:string|null; nextAction:string|null; remarks:string|null; travelCostKes:number|null; consentToContact:boolean; updatedAt:string };
const blank = { schoolName:"",county:"",town:"",locationNotes:"",schoolType:"",estimatedLearners:"",contactName:"",contactRole:"",contactPhone:"",contactEmail:"",stage:"PLANNED" as Stage,visitAt:"",meetingAt:"",followUpAt:"",outcome:"",painPoints:"",interestedModules:"",objections:"",currentSystem:"",budgetNotes:"",decisionProcess:"",nextAction:"",remarks:"",travelCostKes:"",consentToContact:false };
const stages: Stage[] = ["PLANNED","VISITED","FOLLOW_UP","DEMO_BOOKED","PILOT_PROPOSED","WON","LOST","NOT_NOW"];
const dt = (v:string|null) => v ? new Date(v).toLocaleString("en-KE",{dateStyle:"medium",timeStyle:"short"}) : "—";
const inputDt = (v:string|null) => v ? new Date(v).toISOString().slice(0,16) : "";

export function SchoolVisitsOpsTab() {
  const { toast } = useToast(); const [visits,setVisits]=React.useState<Visit[]>([]); const [loading,setLoading]=React.useState(true); const [saving,setSaving]=React.useState(false); const [editing,setEditing]=React.useState<string|null>(null); const [form,setForm]=React.useState(blank); const [q,setQ]=React.useState(""); const [stageFilter,setStageFilter]=React.useState("ACTIVE");
  const load=React.useCallback(async()=>{setLoading(true);try{const r=await fetch("/api/ops/school-visits");const j=await r.json();if(j.ok)setVisits(j.data.visits);}finally{setLoading(false);}},[]); React.useEffect(()=>{void load();},[load]);
  function edit(v:Visit){setEditing(v.id);setForm({schoolName:v.schoolName,county:v.county||"",town:v.town||"",locationNotes:v.locationNotes||"",schoolType:v.schoolType||"",estimatedLearners:v.estimatedLearners?String(v.estimatedLearners):"",contactName:v.contactName||"",contactRole:v.contactRole||"",contactPhone:v.contactPhone||"",contactEmail:v.contactEmail||"",stage:v.stage,visitAt:inputDt(v.visitAt),meetingAt:inputDt(v.meetingAt),followUpAt:inputDt(v.followUpAt),outcome:v.outcome||"",painPoints:v.painPoints||"",interestedModules:v.interestedModules||"",objections:v.objections||"",currentSystem:v.currentSystem||"",budgetNotes:v.budgetNotes||"",decisionProcess:v.decisionProcess||"",nextAction:v.nextAction||"",remarks:v.remarks||"",travelCostKes:v.travelCostKes?String(v.travelCostKes):"",consentToContact:v.consentToContact});window.scrollTo({top:0,behavior:"smooth"});}
  async function save(){setSaving(true);try{const visit={...form,id:editing||undefined,estimatedLearners:form.estimatedLearners?Number(form.estimatedLearners):null,travelCostKes:form.travelCostKes?Number(form.travelCostKes):null,visitAt:form.visitAt||null,meetingAt:form.meetingAt||null,followUpAt:form.followUpAt||null};const r=await fetch("/api/ops/school-visits",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({visit})});const j=await r.json();if(!j.ok){toast({title:j.error?.message||"Could not save visit",tone:"error"});return;}toast({title:editing?"School visit updated":"School visit planned",tone:"success"});setForm(blank);setEditing(null);await load();}finally{setSaving(false);}}
  async function remove(id:string){if(!confirm("Delete this school visit record?"))return;await fetch("/api/ops/school-visits",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"delete",id})});await load();}
  const now=Date.now(); const active=visits.filter(v=>!["WON","LOST","NOT_NOW"].includes(v.stage)); const overdue=active.filter(v=>v.followUpAt&&new Date(v.followUpAt).getTime()<now); const upcoming=active.filter(v=>v.meetingAt&&new Date(v.meetingAt).getTime()>=now); const cost=visits.reduce((n,v)=>n+(v.travelCostKes||0),0);
  const shown=visits.filter(v=>{const text=`${v.schoolName} ${v.county||""} ${v.town||""} ${v.contactName||""}`.toLowerCase();const stageOk=stageFilter==="ALL"||(stageFilter==="ACTIVE"?!["WON","LOST","NOT_NOW"].includes(v.stage):v.stage===stageFilter);return stageOk&&text.includes(q.toLowerCase());});
  const set=(k:keyof typeof blank,v:any)=>setForm(f=>({...f,[k]:v}));
  return <div className="space-y-6 text-navy-900 dark:text-navy-100">
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Stat label="Active schools" value={active.length}/><Stat label="Overdue follow-ups" value={overdue.length} danger={overdue.length>0}/><Stat label="Upcoming meetings" value={upcoming.length}/><Stat label="Recorded travel" value={formatKES(cost)}/></div>
    <Card className="border-navy-200 bg-warm-50/80 dark:border-navy-700 dark:bg-navy-900"><CardHeader><CardTitle className="flex items-center gap-2"><Building2 className="h-5 w-5 text-green-600"/>{editing?"Update school visit":"Plan or record a school visit"}</CardTitle><p className="text-xs text-navy-500">Record only business contact information shared for follow-up. Do not collect learner records or unrelated personal information during sales visits.</p></CardHeader><CardContent className="space-y-4">
      <Section title="School and contact"><Field label="School name *"><Input value={form.schoolName} onChange={e=>set("schoolName",e.target.value)} placeholder="School name"/></Field><Field label="County"><Input value={form.county} onChange={e=>set("county",e.target.value)} placeholder="Nairobi"/></Field><Field label="Town / area"><Input value={form.town} onChange={e=>set("town",e.target.value)} placeholder="Westlands"/></Field><Field label="School type"><Input value={form.schoolType} onChange={e=>set("schoolType",e.target.value)} placeholder="Private day secondary"/></Field><Field label="Estimated learners"><Input type="number" min="1" value={form.estimatedLearners} onChange={e=>set("estimatedLearners",e.target.value)}/></Field><Field label="Contact name"><Input value={form.contactName} onChange={e=>set("contactName",e.target.value)}/></Field><Field label="Contact role"><Input value={form.contactRole} onChange={e=>set("contactRole",e.target.value)} placeholder="Principal / Director / Bursar"/></Field><Field label="Phone"><Input value={form.contactPhone} onChange={e=>set("contactPhone",e.target.value)} placeholder="+254…"/></Field><Field label="Email"><Input type="email" value={form.contactEmail} onChange={e=>set("contactEmail",e.target.value)}/></Field></Section>
      <Section title="Schedule and pipeline"><Field label="Stage"><select value={form.stage} onChange={e=>set("stage",e.target.value)} className="h-12 w-full rounded-2xl border px-3 dark:bg-navy-900">{stages.map(s=><option key={s}>{s}</option>)}</select></Field><Field label="Physical visit"><Input type="datetime-local" value={form.visitAt} onChange={e=>set("visitAt",e.target.value)}/></Field><Field label="Scheduled meeting / demo"><Input type="datetime-local" value={form.meetingAt} onChange={e=>set("meetingAt",e.target.value)}/></Field><Field label="Next follow-up"><Input type="datetime-local" value={form.followUpAt} onChange={e=>set("followUpAt",e.target.value)}/></Field><Field label="Travel cost (KES)"><Input type="number" min="0" value={form.travelCostKes} onChange={e=>set("travelCostKes",e.target.value)}/></Field><Field label="Location / directions"><Input value={form.locationNotes} onChange={e=>set("locationNotes",e.target.value)} placeholder="Gate, landmark or appointment instructions"/></Field></Section>
      <Section title="Discovery and decision"><Area label="Pain points heard" value={form.painPoints} onChange={v=>set("painPoints",v)}/><Area label="Interested NEYO workflows" value={form.interestedModules} onChange={v=>set("interestedModules",v)}/><Area label="Current system or workaround" value={form.currentSystem} onChange={v=>set("currentSystem",v)}/><Area label="Objections / concerns" value={form.objections} onChange={v=>set("objections",v)}/><Area label="Budget / buying window" value={form.budgetNotes} onChange={v=>set("budgetNotes",v)}/><Area label="Decision process and people" value={form.decisionProcess} onChange={v=>set("decisionProcess",v)}/><Area label="Meeting outcome" value={form.outcome} onChange={v=>set("outcome",v)}/><Area label="Next physical action" value={form.nextAction} onChange={v=>set("nextAction",v)}/><Area label="Other remarks" value={form.remarks} onChange={v=>set("remarks",v)}/></Section>
      <label className="flex items-start gap-2 rounded-xl border p-3 text-sm"><input type="checkbox" checked={form.consentToContact} onChange={e=>set("consentToContact",e.target.checked)} className="mt-1"/><span><strong>Permission to follow up recorded</strong><span className="block text-xs text-navy-500">Tick only when the contact agreed to receive follow-up communication. This is not consent for marketing to parents or learners.</span></span></label>
      <div className="flex justify-end gap-2">{editing&&<Button variant="secondary" onClick={()=>{setEditing(null);setForm(blank);}}>Cancel edit</Button>}<Button onClick={save} disabled={saving||!form.schoolName.trim()}>{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<CheckCircle2 className="h-4 w-4"/>}{editing?"Save changes":"Save school visit"}</Button></div>
    </CardContent></Card>
    <div className="flex flex-col gap-3 sm:flex-row"><div className="flex flex-1 items-center gap-2 rounded-2xl border px-3"><Search className="h-4 w-4 text-navy-400"/><input className="h-11 w-full bg-transparent text-sm outline-none" placeholder="Search school, town or contact" value={q} onChange={e=>setQ(e.target.value)}/></div><select value={stageFilter} onChange={e=>setStageFilter(e.target.value)} className="h-11 rounded-2xl border px-3 dark:bg-navy-900"><option>ACTIVE</option><option>ALL</option>{stages.map(s=><option key={s}>{s}</option>)}</select></div>
    {loading?<div className="flex justify-center p-12"><Loader2 className="h-7 w-7 animate-spin"/></div>:shown.length===0?<Card className="border-navy-200 bg-warm-50/80 dark:border-navy-700 dark:bg-navy-900"><CardContent className="py-10 text-center text-sm text-navy-400">No school visits in this view.</CardContent></Card>:<div className="grid gap-4 lg:grid-cols-2">{shown.map(v=>{const late=v.followUpAt&&new Date(v.followUpAt).getTime()<now&&!["WON","LOST","NOT_NOW"].includes(v.stage);return <Card key={v.id} className={late?"border-red-300":""}><CardContent className="space-y-3 p-4"><div className="flex items-start justify-between gap-2"><div><div className="flex flex-wrap gap-1"><Badge tone={v.stage==="WON"?"green":late?"red":"blue"}>{v.stage.replace("_"," ")}</Badge>{v.schoolType&&<Badge tone="neutral">{v.schoolType}</Badge>}</div><h3 className="mt-2 text-lg font-bold">{v.schoolName}</h3><p className="flex items-center gap-1 text-xs text-navy-500"><MapPin className="h-3 w-3"/>{[v.town,v.county].filter(Boolean).join(", ")||"Location not recorded"}</p></div><div className="flex"><button onClick={()=>edit(v)} className="p-2 text-navy-400 hover:text-green-700"><Pencil className="h-4 w-4"/></button><button onClick={()=>remove(v.id)} className="p-2 text-navy-400 hover:text-red-600"><Trash2 className="h-4 w-4"/></button></div></div>{v.contactName&&<p className="text-sm"><strong>{v.contactName}</strong>{v.contactRole?` • ${v.contactRole}`:""}{v.contactPhone&&<span className="ml-2 inline-flex items-center gap-1 text-xs text-navy-500"><Phone className="h-3 w-3"/>{v.contactPhone}</span>}</p>}<div className="grid grid-cols-2 gap-2 text-xs"><Info label="Visit" value={dt(v.visitAt)}/><Info label="Meeting" value={dt(v.meetingAt)}/><Info label="Follow-up" value={dt(v.followUpAt)} danger={Boolean(late)}/><Info label="Learners" value={v.estimatedLearners?String(v.estimatedLearners):"—"}/></div>{v.painPoints&&<p className="text-xs text-navy-600"><strong>Pain:</strong> {v.painPoints}</p>}{v.objections&&<p className="text-xs text-amber-700"><strong>Concern:</strong> {v.objections}</p>}{v.nextAction&&<p className="rounded-xl bg-green-50 p-2 text-sm text-green-900 dark:bg-green-950/20 dark:text-green-100"><strong>Next:</strong> {v.nextAction}</p>}{!v.consentToContact&&<p className="text-xs text-red-600">Follow-up permission not recorded.</p>}</CardContent></Card>;})}</div>}
  </div>;
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <fieldset><legend className="mb-2 text-sm font-bold">{title}</legend><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{children}</div></fieldset>;} function Field({label,children}:{label:string;children:React.ReactNode}){return <label><Label>{label}</Label>{children}</label>;} function Area({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label><Label>{label}</Label><textarea rows={3} value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-2xl border px-3 py-2 text-sm dark:bg-navy-900"/></label>;} function Stat({label,value,danger=false}:{label:string;value:string|number;danger?:boolean}){return <Card className="border-navy-200 bg-warm-50/80 dark:border-navy-700 dark:bg-navy-900"><CardContent className="p-4"><p className="text-xs text-navy-400">{label}</p><p className={`text-2xl font-black ${danger?"text-red-600":""}`}>{value}</p></CardContent></Card>;} function Info({label,value,danger=false}:{label:string;value:string;danger?:boolean}){return <div className={`rounded-lg bg-warm-50 p-2 dark:bg-navy-900 ${danger?"text-red-600":""}`}><span className="block text-navy-400">{label}</span><strong>{value}</strong></div>;}
