import { chromium } from "playwright";
import { db } from "../src/lib/db";

const BASE=process.env.NEYO_TEST_BASE_URL||"http://localhost:3000";
const EMAIL=process.env.NEYO_TEST_EMAIL||"principal@karibuhigh.ac.ke";
const PASSWORD=process.env.NEYO_TEST_PASSWORD||"Karibu2026!";
const check=(ok:unknown,msg:string)=>{if(!ok)throw new Error(`FAIL: ${msg}`);console.log(`PASS: ${msg}`)};

async function main(){const tenant=await db.tenant.findUniqueOrThrow({where:{slug:"karibu-high"}});const suffix=Date.now().toString(36);const student=await db.student.create({data:{tenantId:tenant.id,admissionNo:`OFF-${suffix}`,firstName:"Offline",lastName:"Proof",gender:"F",status:"ACTIVE"}as never});const reason=`Exactly once browser ${suffix}`;const key=`offline-browser-${suffix}`;const invalidKey=`offline-invalid-${suffix}`;const browser=await chromium.launch();try{const context=await browser.newContext();const page=await context.newPage();await page.goto(`${BASE}/login`,{waitUntil:"domcontentloaded"});const login=await page.evaluate(async({email,password})=>fetch("/api/auth/password/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})}).then(r=>r.json()),{email:EMAIL,password:PASSWORD});check(login.ok,"real password login succeeded");await page.goto(`${BASE}/dashboard`,{waitUntil:"domcontentloaded"});
const enqueue=async(id:string,body:any)=>page.evaluate(async({id,body})=>{const db=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open("neyo-offline",3);r.onupgradeneeded=()=>{for(const [name,keyPath]of [["outbox","id"],["bundleCache","key"],["failedOutbox","id"]]as const)if(!r.result.objectStoreNames.contains(name))r.result.createObjectStore(name,{keyPath})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});await new Promise<void>((resolve,reject)=>{const tx=db.transaction("outbox","readwrite");tx.objectStore("outbox").put({id,url:"/api/security",body,label:"Offline exactly-once gate pass",createdAt:Date.now()});tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});},{id,body});
await context.setOffline(true);await enqueue(key,{action:"gatePass",studentId:student.id,reason,leaveAt:new Date().toISOString()});await context.setOffline(false);await page.evaluate(()=>window.dispatchEvent(new Event("online")));await page.waitForTimeout(2500);await page.evaluate(()=>window.dispatchEvent(new Event("online")));await page.waitForTimeout(1200);check(await db.gatePass.count({where:{tenantId:tenant.id,reason}})===1,"offline reconnect and repeated sync created exactly one gate pass");check(await db.idempotentRequest.count({where:{tenantId:tenant.id,action:"security.gatePass",idempotencyKey:key}})===1,"exactly one replay receipt exists");
await context.setOffline(true);await enqueue(invalidKey,{action:"gatePass",studentId:"missing-student",reason:"Invalid offline proof",leaveAt:new Date().toISOString()});await context.setOffline(false);await page.evaluate(()=>window.dispatchEvent(new Event("online")));await page.waitForTimeout(2000);const failed=await page.evaluate(async()=>{const db=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open("neyo-offline",3);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return new Promise<any[]>((resolve,reject)=>{const r=db.transaction("failedOutbox","readonly").objectStore("failedOutbox").getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})});check(failed.some(row=>row.id===invalidKey&&row.reason),"permanent rejected sync remained in failed review inbox");console.log("OFFLINE BROWSER EXACTLY-ONCE COMPLETE");}finally{await browser.close();await db.gatePass.deleteMany({where:{tenantId:tenant.id,reason}});await db.idempotentRequest.deleteMany({where:{tenantId:tenant.id,idempotencyKey:{in:[key,invalidKey]}}});await db.student.delete({where:{id:student.id}}).catch(()=>{});await db.$disconnect();}}
main().catch(async e=>{console.error(e);await db.$disconnect();process.exit(1)});
