export const NEYO_PRIVACY_VERSION="2026-07-21";
export const NEYO_PRIVACY_EFFECTIVE_DATE="21 July 2026";
export const NEYO_PRIVACY_SECTIONS=[
{title:"1. Scope",text:"This policy explains how NEYO handles personal data through its websites, demo requests, pilot environments and School OS services. Actual processing depends on the modules and integrations a customer enables."},
{title:"2. Roles and responsibility",text:"A school or organisation generally determines why and how its learner, guardian and staff records are used and is responsible for its notices, permissions, accuracy, releases and user access. NEYO processes customer data to provide and secure the service. NEYO may separately control limited account, website, commercial, security and support data for its own legitimate operations. Exact legal roles depend on the context and applicable agreement."},
{title:"3. Data handled",bullets:["Account and identity details such as name, role, phone, email and login identifiers.","School records such as admissions, classes, attendance, fees, payments, assessments, competencies, timetables, communications and documents.","Sensitive records a school chooses to use, such as health, discipline, safeguarding or biometric/passkey references.","Technical, security and audit information such as device/session details, IP address, sign-in and action logs.","Demo, quote, support, interview and school-contact information."]},
{title:"4. Purposes",bullets:["Provide, authenticate, secure and support NEYO.","Process school workflows and produce requested documents, messages and reports.","Prevent fraud, misuse and cross-school access.","Maintain audit, backup, recovery, billing and service-health records.","Improve product reliability using appropriately limited operational information.","Meet legal obligations and respond to valid requests."]},
{title:"5. Sharing and providers",text:"NEYO may use contracted infrastructure, payment, messaging, email, storage, authentication, support and monitoring providers when configured. Data is shared only as needed for the relevant service and subject to applicable safeguards. NEYO does not claim a government integration unless it is expressly shown as connected and verified."},
{title:"6. Security",text:"NEYO uses controls including role permissions, tenant isolation, password hashing, encrypted credential/file paths, HTTPS, rate limiting, audit logs and security challenges where configured. No system is absolutely secure. Customers must manage users, devices and exports responsibly and report suspected incidents promptly."},
{title:"7. Retention",text:"Retention depends on school policy, contract, record type, backups and legal, financial, safeguarding and audit requirements. Temporary files may follow lifecycle deletion rules. A deletion request may not remove information that must lawfully or securely be retained."},
{title:"8. Individual rights",text:"Depending on Kenyan law and the context, individuals may have rights to information, access, correction, objection, restriction, portability or erasure. For school-controlled records, contact the school first. NEYO will assist customers and respond to requests for data NEYO controls, subject to identity verification and lawful exceptions."},
{title:"9. Children",text:"Schools must provide appropriate notices and authority for processing children’s data and must configure parent/learner access carefully. NEYO does not permit public exposure of private learner records through ordinary School OS pages."},
{title:"10. International processing and changes",text:"Some approved service providers may process data outside Kenya. Appropriate contractual and legal safeguards should be assessed before production activation. This policy may be updated with a new effective date and reasonable notice for material changes."},
{title:"11. Contact",text:"Privacy questions or requests may be sent to hello@neyo.co.ke. NEYO will publish a dedicated privacy or Data Protection Officer contact only after the relevant appointment and operational process are formally established."}
] as const;
