import { z } from "zod";
import { db } from "@/lib/db";
import type { SessionUser } from "@/lib/core/session";

const KEY="onboarding_fee_engine_v1";
export const onboardingFeeConfigSchema=z.object({version:z.number().int().min(1).default(1),baseEnabled:z.boolean(),baseKes:z.number().int().min(0),studentsEnabled:z.boolean(),perStudentKes:z.number().min(0),staffEnabled:z.boolean(),perStaffKes:z.number().min(0),campusesEnabled:z.boolean(),perAdditionalCampusKes:z.number().int().min(0),boardingEnabled:z.boolean(),boardingKes:z.number().int().min(0),migrationEnabled:z.boolean(),perHundredMigrationRowsKes:z.number().int().min(0),trainingEnabled:z.boolean(),perTrainingSessionKes:z.number().int().min(0),minimumKes:z.number().int().min(0),maximumKes:z.number().int().min(0).nullable()});
export type OnboardingFeeConfig=z.infer<typeof onboardingFeeConfigSchema>;
export const DEFAULT_ONBOARDING_FEE:OnboardingFeeConfig={version:1,baseEnabled:true,baseKes:5000,studentsEnabled:true,perStudentKes:10,staffEnabled:false,perStaffKes:0,campusesEnabled:true,perAdditionalCampusKes:3000,boardingEnabled:true,boardingKes:3000,migrationEnabled:true,perHundredMigrationRowsKes:1000,trainingEnabled:true,perTrainingSessionKes:1500,minimumKes:0,maximumKes:null};
export const onboardingInputsSchema=z.object({tenantId:z.string().optional(),schoolQuoteRequestId:z.string().optional(),schoolName:z.string().trim().min(2).max(160),studentCount:z.coerce.number().int().min(0),staffCount:z.coerce.number().int().min(0),campusCount:z.coerce.number().int().min(1).default(1),boarding:z.boolean().default(false),migrationRows:z.coerce.number().int().min(0).default(0),trainingSessions:z.coerce.number().int().min(0).default(0)});

export async function getOnboardingFeeConfig(){const row=await db.platformSetting.findUnique({where:{key:KEY}});if(!row)return DEFAULT_ONBOARDING_FEE;try{return onboardingFeeConfigSchema.parse(JSON.parse(row.value));}catch{return DEFAULT_ONBOARDING_FEE;}}
export async function saveOnboardingFeeConfig(actor:SessionUser,raw:unknown){const cfg=onboardingFeeConfigSchema.parse(raw);await db.platformSetting.upsert({where:{key:KEY},create:{key:KEY,value:JSON.stringify(cfg),updatedBy:actor.fullName},update:{value:JSON.stringify(cfg),updatedBy:actor.fullName}});await db.auditLog.create({data:{tenantId:actor.tenantId,actorId:actor.id,actorName:actor.fullName,action:"platform.onboarding_fee_config_updated",entityType:"PlatformSetting",entityId:KEY,metadata:JSON.stringify(cfg)}});return cfg;}
export function calculateOnboardingFee(input:z.infer<typeof onboardingInputsSchema>,cfg:OnboardingFeeConfig){const lines=[{key:"base",label:"Base onboarding",enabled:cfg.baseEnabled,amount:cfg.baseKes},{key:"students",label:`${input.studentCount} learners`,enabled:cfg.studentsEnabled,amount:Math.round(input.studentCount*cfg.perStudentKes)},{key:"staff",label:`${input.staffCount} staff`,enabled:cfg.staffEnabled,amount:Math.round(input.staffCount*cfg.perStaffKes)},{key:"campuses",label:`${Math.max(0,input.campusCount-1)} additional campuses`,enabled:cfg.campusesEnabled,amount:Math.max(0,input.campusCount-1)*cfg.perAdditionalCampusKes},{key:"boarding",label:"Boarding setup",enabled:cfg.boardingEnabled&&input.boarding,amount:cfg.boardingKes},{key:"migration",label:`${input.migrationRows} migration rows`,enabled:cfg.migrationEnabled,amount:Math.ceil(input.migrationRows/100)*cfg.perHundredMigrationRowsKes},{key:"training",label:`${input.trainingSessions} training sessions`,enabled:cfg.trainingEnabled,amount:input.trainingSessions*cfg.perTrainingSessionKes}].filter(x=>x.enabled&&x.amount>0);let total=lines.reduce((n,x)=>n+x.amount,0);total=Math.max(cfg.minimumKes,total);if(cfg.maximumKes!=null)total=Math.min(cfg.maximumKes,total);return{totalKes:total,display:total===0?"FREE":`KES ${total.toLocaleString("en-KE")}`,lines};}
export async function createOnboardingFeeQuote(actor:SessionUser,raw:unknown){let input=onboardingInputsSchema.parse(raw);if(input.tenantId){const [tenant,students,staff]=await Promise.all([db.tenant.findUnique({where:{id:input.tenantId},select:{name:true}}),db.student.count({where:{tenantId:input.tenantId,status:"ACTIVE",deletedAt:null}}),db.user.count({where:{tenantId:input.tenantId,isActive:true,role:{notIn:["PARENT","STUDENT"]}}})]);if(!tenant)throw new Error("School not found.");input={...input,schoolName:tenant.name,studentCount:students,staffCount:staff};}const cfg=await getOnboardingFeeConfig();const result=calculateOnboardingFee(input,cfg);return db.onboardingFeeQuote.create({data:{tenantId:input.tenantId||null,schoolQuoteRequestId:input.schoolQuoteRequestId||null,schoolName:input.schoolName,inputJson:JSON.stringify(input),breakdownJson:JSON.stringify(result.lines),formulaVersion:cfg.version,calculatedFeeKes:result.totalKes,createdById:actor.id,createdByName:actor.fullName}});}
export async function reviewOnboardingFeeQuote(actor:SessionUser,raw:unknown){const input=z.object({id:z.string().min(1),finalFeeKes:z.coerce.number().int().min(0),waiverReason:z.string().trim().max(500).optional()}).parse(raw);if(input.finalFeeKes===0&&!input.waiverReason)throw new Error("Explain why this onboarding fee is FREE.");const row=await db.onboardingFeeQuote.update({where:{id:input.id},data:{finalFeeKes:input.finalFeeKes,status:input.finalFeeKes===0?"WAIVED":"REVIEWED",waiverReason:input.finalFeeKes===0?input.waiverReason:null,reviewedById:actor.id,reviewedByName:actor.fullName,reviewedAt:new Date()}});await db.auditLog.create({data:{tenantId:row.tenantId||actor.tenantId,actorId:actor.id,actorName:actor.fullName,action:"platform.onboarding_fee_reviewed",entityType:"OnboardingFeeQuote",entityId:row.id,metadata:JSON.stringify({calculatedFeeKes:row.calculatedFeeKes,finalFeeKes:row.finalFeeKes,status:row.status,waiverReason:row.waiverReason})}});return row;}
export async function listOnboardingFeeQuotes(){return db.onboardingFeeQuote.findMany({orderBy:{updatedAt:"desc"},take:300});}

const DEFAULT_CHECKLIST = [
  { key: "scope", label: "Confirm onboarding scope and owners", done: false },
  { key: "data", label: "Map and verify school data", done: false },
  { key: "configuration", label: "Configure school structures and modules", done: false },
  { key: "training", label: "Complete role-by-role staff training", done: false },
  { key: "pilot", label: "Run and verify pilot workflows", done: false },
  { key: "go_live", label: "Approve controlled go-live", done: false },
];

async function activateOnboardingRun(quoteId:string){const quote=await db.onboardingFeeQuote.findUnique({where:{id:quoteId}});if(!quote)throw new Error("Onboarding quote not found.");return db.onboardingRun.upsert({where:{quoteId},create:{quoteId,tenantId:quote.tenantId,schoolName:quote.schoolName,checklistJson:JSON.stringify(DEFAULT_CHECKLIST)},update:{status:"ACTIVE"}});}

export async function approveOnboardingQuote(user:SessionUser,id:string){const quote=await db.onboardingFeeQuote.findFirst({where:{id,tenantId:user.tenantId}});if(!quote||!["REVIEWED","WAIVED"].includes(quote.status))throw new Error("A Founder-reviewed onboarding quote is required first.");const approved=await db.onboardingFeeQuote.update({where:{id},data:{status:"APPROVED",approvedAt:new Date()}});if((approved.finalFeeKes??approved.calculatedFeeKes)===0)await activateOnboardingRun(approved.id);await db.auditLog.create({data:{tenantId:user.tenantId,actorId:user.id,actorName:user.fullName,action:"onboarding.quote_approved_by_school",entityType:"OnboardingFeeQuote",entityId:id,metadata:JSON.stringify({finalFeeKes:approved.finalFeeKes??approved.calculatedFeeKes})}});return approved;}

function onboardingCallbackUrl(){const base=(process.env.NEXT_PUBLIC_APP_URL||"https://www.neyo.co.ke").replace(/\/$/,"");const token=process.env.DARAJA_WEBHOOK_TOKEN;return `${base}/api/onboarding-fee/callback${token?`?t=${encodeURIComponent(token)}`:""}`;}

export async function initiateOnboardingPayment(user:SessionUser,raw:unknown){const input=z.object({quoteId:z.string().min(1),phone:z.string().trim().regex(/^(?:\+254|0)[17]\d{8}$/)}).parse(raw);const phone=input.phone.startsWith("0")?`+254${input.phone.slice(1)}`:input.phone;const quote=await db.onboardingFeeQuote.findFirst({where:{id:input.quoteId,tenantId:user.tenantId,status:"APPROVED"}});if(!quote)throw new Error("Approve the reviewed onboarding quote first.");const amount=quote.finalFeeKes??quote.calculatedFeeKes;if(amount===0){const run=await activateOnboardingRun(quote.id);return{free:true,run};}const accountRef=`ONBOARD-${quote.id}`.slice(0,20);const payment=await db.onboardingPayment.create({data:{quoteId:quote.id,amountKes:amount,phone,status:"PENDING",accountRef}});const{centralGateway}=await import("@/lib/services/central-billing.service");const gateway=await centralGateway();const result=await gateway.provider.stkPush(gateway.creds,{amount,phone,accountRef,description:`NEYO Onboarding ${quote.schoolName}`.slice(0,60),callbackUrl:onboardingCallbackUrl()});if(!result.ok||!result.checkoutRequestId){await db.onboardingPayment.update({where:{id:payment.id},data:{status:"FAILED",resultDesc:result.message}});throw new Error(result.message||"Could not start onboarding payment.");}const updated=await db.onboardingPayment.update({where:{id:payment.id},data:{checkoutRequestId:result.checkoutRequestId}});await db.auditLog.create({data:{tenantId:user.tenantId,actorId:user.id,actorName:user.fullName,action:"onboarding.payment_started",entityType:"OnboardingPayment",entityId:updated.id,metadata:JSON.stringify({quoteId:quote.id,amountKes:amount,provider:gateway.provider.key,live:gateway.live})}});return{free:false,payment:updated};}

export async function handleOnboardingPaymentCallback(body:unknown){const raw=body as any;let parsed:any;if(raw?.Body?.stkCallback){const{DarajaProvider}=await import("@/lib/payments/daraja-provider");parsed=new DarajaProvider().parseCallback(body);}else parsed={checkoutRequestId:raw.checkoutRequestId||raw.CheckoutRequestID,status:raw.success===false?"FAILED":"PAID",mpesaRef:raw.mpesaRef||raw.MpesaReceiptNumber||raw.TransID||null,resultCode:String(raw.resultCode||raw.ResultCode||0),resultDesc:raw.resultDesc||raw.ResultDesc||"Success"};if(!parsed.checkoutRequestId)return{matched:false};const payment=await db.onboardingPayment.findUnique({where:{checkoutRequestId:parsed.checkoutRequestId}});if(!payment)return{matched:false};if(payment.status==="PAID")return{matched:true,status:"PAID"};if(parsed.status!=="PAID"){await db.onboardingPayment.update({where:{id:payment.id},data:{status:"FAILED",resultCode:parsed.resultCode,resultDesc:parsed.resultDesc,rawCallback:JSON.stringify(body)}});return{matched:true,status:"FAILED"};}if(parsed.mpesaRef){const duplicate=await db.onboardingPayment.findUnique({where:{mpesaRef:parsed.mpesaRef}});if(duplicate&&duplicate.id!==payment.id)throw new Error("This M-Pesa reference is already recorded.");}await db.$transaction([db.onboardingPayment.update({where:{id:payment.id},data:{status:"PAID",mpesaRef:parsed.mpesaRef,paidAt:new Date(),resultCode:parsed.resultCode,resultDesc:parsed.resultDesc,rawCallback:JSON.stringify(body)}}),db.onboardingFeeQuote.update({where:{id:payment.quoteId},data:{status:"PAID"}})]);const run=await activateOnboardingRun(payment.quoteId);const quote=await db.onboardingFeeQuote.findUnique({where:{id:payment.quoteId}});await db.auditLog.create({data:{tenantId:quote?.tenantId||payment.quoteId,actorName:"NEYO Onboarding M-Pesa",action:"onboarding.payment_confirmed",entityType:"OnboardingPayment",entityId:payment.id,metadata:JSON.stringify({quoteId:payment.quoteId,amountKes:payment.amountKes,mpesaRef:parsed.mpesaRef,runId:run.id})}});return{matched:true,status:"PAID",runId:run.id};}

export async function currentOnboardingForTenant(tenantId:string){const quote=await db.onboardingFeeQuote.findFirst({where:{tenantId},orderBy:{updatedAt:"desc"}});if(!quote)return{quote:null,payments:[],run:null};const[payments,run]=await Promise.all([db.onboardingPayment.findMany({where:{quoteId:quote.id},orderBy:{createdAt:"desc"}}),db.onboardingRun.findUnique({where:{quoteId:quote.id}})]);return{quote,payments,run:run?{...run,checklist:JSON.parse(run.checklistJson)}:null};}

export async function updateOnboardingChecklist(user:SessionUser,raw:unknown){const input=z.object({runId:z.string().min(1),key:z.string().min(1),done:z.boolean()}).parse(raw);const run=await db.onboardingRun.findFirst({where:{id:input.runId,tenantId:user.tenantId}});if(!run)throw new Error("Active onboarding checklist not found.");const items=JSON.parse(run.checklistJson)as{key:string;label:string;done:boolean}[];const item=items.find(x=>x.key===input.key);if(!item)throw new Error("Checklist step not found.");item.done=input.done;const complete=items.length>0&&items.every(x=>x.done);const updated=await db.onboardingRun.update({where:{id:run.id},data:{checklistJson:JSON.stringify(items),status:complete?"COMPLETED":"ACTIVE",completedAt:complete?new Date():null}});await db.auditLog.create({data:{tenantId:user.tenantId,actorId:user.id,actorName:user.fullName,action:"onboarding.checklist_updated",entityType:"OnboardingRun",entityId:run.id,metadata:JSON.stringify({key:input.key,done:input.done,status:updated.status})}});return{...updated,checklist:items};}
