import { z } from "zod";
import { db } from "@/lib/db";
import type { SessionUser } from "@/lib/core/session";

const KEY="onboarding_fee_engine_v1";
export const onboardingFeeConfigSchema=z.object({version:z.number().int().min(1).default(1),baseEnabled:z.boolean(),baseKes:z.number().int().min(0),studentsEnabled:z.boolean(),perStudentKes:z.number().min(0),staffEnabled:z.boolean(),perStaffKes:z.number().min(0),campusesEnabled:z.boolean(),perAdditionalCampusKes:z.number().int().min(0),boardingEnabled:z.boolean(),boardingKes:z.number().int().min(0),migrationEnabled:z.boolean(),perHundredMigrationRowsKes:z.number().int().min(0),trainingEnabled:z.boolean(),perTrainingSessionKes:z.number().int().min(0),minimumKes:z.number().int().min(0),maximumKes:z.number().int().min(0).nullable()});
export type OnboardingFeeConfig=z.infer<typeof onboardingFeeConfigSchema>;
export const DEFAULT_ONBOARDING_FEE:OnboardingFeeConfig={version:1,baseEnabled:true,baseKes:5000,studentsEnabled:true,perStudentKes:10,staffEnabled:false,perStaffKes:0,campusesEnabled:true,perAdditionalCampusKes:3000,boardingEnabled:true,boardingKes:3000,migrationEnabled:true,perHundredMigrationRowsKes:1000,trainingEnabled:true,perTrainingSessionKes:1500,minimumKes:0,maximumKes:null};
export const onboardingInputsSchema=z.object({tenantId:z.string().optional(),schoolQuoteRequestId:z.string().optional(),schoolName:z.string().trim().min(2).max(160),studentCount:z.coerce.number().int().min(0),staffCount:z.coerce.number().int().min(0),campusCount:z.coerce.number().int().min(1).default(1),boarding:z.boolean().default(false),migrationRows:z.coerce.number().int().min(0).default(0),trainingSessions:z.coerce.number().int().min(0).default(0)});

export async function getOnboardingFeeConfig(){const row=await db.platformSetting.findUnique({where:{key:KEY}});if(!row)return DEFAULT_ONBOARDING_FEE;try{return onboardingFeeConfigSchema.parse(JSON.parse(row.value));}catch{return DEFAULT_ONBOARDING_FEE;}}
export async function saveOnboardingFeeConfig(actor:SessionUser,raw:unknown){const cfg=onboardingFeeConfigSchema.parse(raw);await db.platformSetting.upsert({where:{key:KEY},create:{key:KEY,value:JSON.stringify(cfg),updatedBy:actor.fullName},update:{value:JSON.stringify(cfg),updatedBy:actor.fullName}});await db.auditLog.create({data:{tenantId:actor.tenantId,actorId:actor.id,actorName:actor.fullName,action:"platform.onboarding_fee_config_updated",entityType:"PlatformSetting",entityId:KEY,metadata:JSON.stringify(cfg)}});return cfg;}
export function calculateOnboardingFee(input:z.infer<typeof onboardingInputsSchema>,cfg:OnboardingFeeConfig){const lines=[{key:"base",label:"Base onboarding",enabled:cfg.baseEnabled,amount:cfg.baseKes},{key:"students",label:`${input.studentCount} learners`,enabled:cfg.studentsEnabled,amount:Math.round(input.studentCount*cfg.perStudentKes)},{key:"staff",label:`${input.staffCount} staff`,enabled:cfg.staffEnabled,amount:Math.round(input.staffCount*cfg.perStaffKes)},{key:"campuses",label:`${Math.max(0,input.campusCount-1)} additional campuses`,enabled:cfg.campusesEnabled,amount:Math.max(0,input.campusCount-1)*cfg.perAdditionalCampusKes},{key:"boarding",label:"Boarding setup",enabled:cfg.boardingEnabled&&input.boarding,amount:cfg.boardingKes},{key:"migration",label:`${input.migrationRows} migration rows`,enabled:cfg.migrationEnabled,amount:Math.ceil(input.migrationRows/100)*cfg.perHundredMigrationRowsKes},{key:"training",label:`${input.trainingSessions} training sessions`,enabled:cfg.trainingEnabled,amount:input.trainingSessions*cfg.perTrainingSessionKes}].filter(x=>x.enabled&&x.amount>0);let total=lines.reduce((n,x)=>n+x.amount,0);total=Math.max(cfg.minimumKes,total);if(cfg.maximumKes!=null)total=Math.min(cfg.maximumKes,total);return{totalKes:total,display:total===0?"FREE":`KES ${total.toLocaleString("en-KE")}`,lines};}
export async function createOnboardingFeeQuote(actor:SessionUser,raw:unknown){let input=onboardingInputsSchema.parse(raw);if(input.tenantId){const [tenant,students,staff]=await Promise.all([db.tenant.findUnique({where:{id:input.tenantId},select:{name:true}}),db.student.count({where:{tenantId:input.tenantId,status:"ACTIVE",deletedAt:null}}),db.user.count({where:{tenantId:input.tenantId,isActive:true,role:{notIn:["PARENT","STUDENT"]}}})]);if(!tenant)throw new Error("School not found.");input={...input,schoolName:tenant.name,studentCount:students,staffCount:staff};}const cfg=await getOnboardingFeeConfig();const result=calculateOnboardingFee(input,cfg);return db.onboardingFeeQuote.create({data:{tenantId:input.tenantId||null,schoolQuoteRequestId:input.schoolQuoteRequestId||null,schoolName:input.schoolName,inputJson:JSON.stringify(input),breakdownJson:JSON.stringify(result.lines),formulaVersion:cfg.version,calculatedFeeKes:result.totalKes,createdById:actor.id,createdByName:actor.fullName}});}
export async function reviewOnboardingFeeQuote(actor:SessionUser,raw:unknown){const input=z.object({id:z.string().min(1),finalFeeKes:z.coerce.number().int().min(0),waiverReason:z.string().trim().max(500).optional()}).parse(raw);if(input.finalFeeKes===0&&!input.waiverReason)throw new Error("Explain why this onboarding fee is FREE.");const row=await db.onboardingFeeQuote.update({where:{id:input.id},data:{finalFeeKes:input.finalFeeKes,status:input.finalFeeKes===0?"WAIVED":"REVIEWED",waiverReason:input.finalFeeKes===0?input.waiverReason:null,reviewedById:actor.id,reviewedByName:actor.fullName,reviewedAt:new Date()}});await db.auditLog.create({data:{tenantId:row.tenantId||actor.tenantId,actorId:actor.id,actorName:actor.fullName,action:"platform.onboarding_fee_reviewed",entityType:"OnboardingFeeQuote",entityId:row.id,metadata:JSON.stringify({calculatedFeeKes:row.calculatedFeeKes,finalFeeKes:row.finalFeeKes,status:row.status,waiverReason:row.waiverReason})}});return row;}
export async function listOnboardingFeeQuotes(){return db.onboardingFeeQuote.findMany({orderBy:{updatedAt:"desc"},take:300});}
