import { db } from "@/lib/db";
import type { SessionUser } from "@/lib/core/session";

export const PUBLIC_ASSET_KINDS=["LOGO","WORDMARK","FAVICON","LANDING_MEDIA"] as const;
const settingForKind:Record<string,string|undefined>={LOGO:"neyo_logo_url",WORDMARK:"neyo_wordmark_light_url",FAVICON:"neyo_favicon_url"};
function validMagic(type:string,b:Buffer){if(type==="image/png")return b.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]));if(type==="image/jpeg")return b[0]===0xff&&b[1]===0xd8&&b[b.length-2]===0xff&&b[b.length-1]===0xd9;if(type==="image/webp")return b.subarray(0,4).toString()==="RIFF"&&b.subarray(8,12).toString()==="WEBP";return true;}
function sanitizeSvg(buffer:Buffer){const text=buffer.toString("utf8");if(!/^\s*<svg[\s>]/i.test(text))throw new Error("This is not a valid standalone SVG.");if(/<\s*(script|foreignObject|image|iframe|object|embed)\b|\son[a-z]+\s*=|javascript:|data:text\/html|url\s*\(/i.test(text))throw new Error("SVG contains unsafe scripts, embedded content or external references.");if(!/\bviewBox\s*=\s*["'][^"']+["']/i.test(text)&&!(/\bwidth\s*=/.test(text)&&/\bheight\s*=/.test(text)))throw new Error("SVG needs a viewBox or explicit width and height.");return Buffer.from(text.replace(/<\?xml[^>]*>/gi,"").trim(),"utf8");}
function rasterDimensions(type:string,b:Buffer){if(type==="image/png"&&b.length>=24)return{width:b.readUInt32BE(16),height:b.readUInt32BE(20)};if(type==="image/jpeg"){let i=2;while(i+9<b.length){if(b[i]!==0xff){i++;continue}const marker=b[i+1],len=b.readUInt16BE(i+2);if([0xc0,0xc1,0xc2,0xc3,0xc5,0xc6,0xc7,0xc9,0xca,0xcb,0xcd,0xce,0xcf].includes(marker))return{height:b.readUInt16BE(i+5),width:b.readUInt16BE(i+7)};if(len<2)break;i+=2+len}}if(type==="image/webp"&&b.subarray(12,16).toString()==="VP8X"&&b.length>=30)return{width:1+b.readUIntLE(24,3),height:1+b.readUIntLE(27,3)};return null;}
function assertDimensions(type:string,b:Buffer){if(type==="image/svg+xml")return;const size=rasterDimensions(type,b);if(!size)throw new Error("Could not verify image dimensions. Re-export as PNG, JPEG or extended WebP.");if(size.width<16||size.height<16||size.width>5000||size.height>5000)throw new Error("Image dimensions must be between 16 and 5000 pixels per side.");}
export async function savePublicBrandAsset(actor:SessionUser,input:{kind:string;label:string;mimeType:string;buffer:Buffer}){if(!PUBLIC_ASSET_KINDS.includes(input.kind as any))throw new Error("Unsupported public asset kind.");if(!["image/svg+xml","image/png","image/jpeg","image/webp"].includes(input.mimeType))throw new Error("Use SVG, PNG, JPEG or WebP.");const max=input.mimeType==="image/svg+xml"?250_000:1_500_000;if(input.buffer.length>max)throw new Error(`File is too large. Maximum ${Math.round(max/1000)} KB.`);const bytes=input.mimeType==="image/svg+xml"?sanitizeSvg(input.buffer):input.buffer;if(!validMagic(input.mimeType,bytes))throw new Error("The file content does not match its image type.");assertDimensions(input.mimeType,bytes);const row=await db.publicBrandAsset.create({data:{kind:input.kind,label:input.label.trim().slice(0,120)||input.kind,mimeType:input.mimeType,bytes,byteSize:bytes.length,createdById:actor.id,createdByName:actor.fullName}});await db.auditLog.create({data:{tenantId:actor.tenantId,actorId:actor.id,actorName:actor.fullName,action:"platform.public_brand_asset_uploaded",entityType:"PublicBrandAsset",entityId:row.id,metadata:JSON.stringify({kind:row.kind,mimeType:row.mimeType,byteSize:row.byteSize})}});return{...row,bytes:undefined,url:`/api/public-assets/${row.id}`};}
export async function activatePublicBrandAsset(actor:SessionUser,id:string){const row=await db.publicBrandAsset.findUnique({where:{id}});if(!row)throw new Error("Public asset not found.");await db.$transaction([db.publicBrandAsset.updateMany({where:{kind:row.kind,active:true},data:{active:false,replacedById:id}}),db.publicBrandAsset.update({where:{id},data:{active:true,replacedById:null}})]);const key=settingForKind[row.kind];const url=`/api/public-assets/${row.id}`;if(key)await db.platformSetting.upsert({where:{key},create:{key,value:url,updatedBy:actor.fullName},update:{value:url,updatedBy:actor.fullName}});await db.auditLog.create({data:{tenantId:actor.tenantId,actorId:actor.id,actorName:actor.fullName,action:"platform.public_brand_asset_activated",entityType:"PublicBrandAsset",entityId:id,metadata:JSON.stringify({kind:row.kind,url})}});return{...row,bytes:undefined,url};}
export async function listPublicBrandAssets(){const rows=await db.publicBrandAsset.findMany({orderBy:{createdAt:"desc"},take:100});return rows.map(row=>({...row,bytes:undefined,url:`/api/public-assets/${row.id}`}));}
