import { tenantDb } from "@/lib/core/tenant-db";
import { withTenant } from "@/lib/core/tenant-context";
import type { SessionUser } from "@/lib/core/session";
const parse=<T>(value:string|null|undefined,fallback:T):T=>{try{return value?JSON.parse(value) as T:fallback;}catch{return fallback;}};

export async function teacherElectiveStaffingReport(user:SessionUser){return withTenant(user.tenantId,async()=>{const db=tenantDb();const[blocks,students,selections,teachers,subjects,publishedSlots,continuity,substitutions]=await Promise.all([
 db.electiveBlock.findMany({where:{active:true},include:{classes:true,slots:{orderBy:{sortOrder:"asc"},include:{subjects:true}}}}),
 db.student.findMany({where:{status:"ACTIVE",deletedAt:null},select:{id:true,firstName:true,lastName:true,admissionNo:true,classId:true}}),
 db.studentSubjectSelection.findMany({where:{isConfirmed:true},orderBy:{updatedAt:"desc"},select:{studentId:true,selectedSubjectIds:true,updatedAt:true}}),
 db.user.findMany({where:{isActive:true},select:{id:true,fullName:true,role:true}}),
 db.subject.findMany({where:{archived:false},select:{id:true,name:true,code:true,recommendedMaxGroupSize:true,practicalMaxGroupSize:true,practicalHeavy:true}}),
 db.timetableSlot.findMany({where:{slotType:{in:["ACADEMIC","ELECTIVE_BLOCK"]}},select:{teacherId:true,electiveBlockSlotId:true,dayOfWeek:true,period:true}}),
 db.teacherContinuityAssignment.findMany({where:{active:true},select:{teacherId:true,subjectId:true,locked:true}}),
 db.substituteAssignment.findMany({where:{status:{in:["PROPOSED","CONFIRMED","UNFILLED"]}},select:{originalTeacherId:true,status:true}}),
]);
 const subjectById=new Map(subjects.map(s=>[s.id,s]));const teacherById=new Map(teachers.map(t=>[t.id,t]));const latestChoices=new Map<string,string[]>();for(const selection of selections)if(!latestChoices.has(selection.studentId))latestChoices.set(selection.studentId,parse(selection.selectedSubjectIds,[]));
 const rawGroups=new Map<string,{blockId:string;blockName:string;family:string;subjectId:string;teacherId:string|null;venueId:string|null;classIds:Set<string>;lessons:Set<string>}>();
 for(const block of blocks)for(const slot of block.slots){const family=slot.label.split("·")[0].trim();if(!/^Option [ABC]$/.test(family))continue;for(const row of slot.subjects){const key=`${block.id}:${family}:${row.subjectId}:${row.teacherId??""}`;const group=rawGroups.get(key)??{blockId:block.id,blockName:block.name,family,subjectId:row.subjectId,teacherId:row.teacherId,venueId:row.venueId??row.resolvedVenueId,classIds:new Set<string>(),lessons:new Set<string>()};for(const id of parse<string[]>(row.comboClassIdsJson,block.classes.map(c=>c.classId)))group.classIds.add(id);group.lessons.add(slot.id);rawGroups.set(key,group);}}
 const groups=[...rawGroups.values()].map(group=>{const subject=subjectById.get(group.subjectId);const members=students.filter(student=>student.classId&&group.classIds.has(student.classId)&&(latestChoices.get(student.id)??[]).includes(group.subjectId));const threshold=subject?.practicalHeavy?(subject.practicalMaxGroupSize??subject.recommendedMaxGroupSize):(subject?.recommendedMaxGroupSize??subject?.practicalMaxGroupSize);const requiredGroups=threshold&&threshold>0?Math.ceil(members.length/threshold):1;return{blockId:group.blockId,blockName:group.blockName,family:group.family,subjectId:group.subjectId,subjectName:subject?.name??"Subject",subjectCode:subject?.code??"",teacherId:group.teacherId,teacherName:group.teacherId?teacherById.get(group.teacherId)?.fullName??"Unknown teacher":null,venueId:group.venueId,classIds:[...group.classIds],lessonsPerWeek:group.lessons.size,studentCount:members.length,studentIds:members.map(m=>m.id),students:members.map(m=>({id:m.id,name:`${m.firstName} ${m.lastName}`,admissionNo:m.admissionNo})),practicalHeavy:subject?.practicalHeavy??false,maxGroupSize:threshold??null,requiredTeachingGroups:Math.max(1,requiredGroups),needsSplit:Boolean(threshold&&members.length>threshold),staffingGap:!group.teacherId};});
 const electiveTeachersBySlot=new Map<string,Set<string>>();for(const block of blocks)for(const slot of block.slots){const set=new Set(slot.subjects.map(row=>row.teacherId).filter((id):id is string=>Boolean(id)));electiveTeachersBySlot.set(slot.id,set);}const teacherRows=teachers.map(teacher=>{const own=groups.filter(g=>g.teacherId===teacher.id);if(!own.length)return null;const unique=new Set(own.flatMap(g=>g.studentIds));const enrolments=own.reduce((s,g)=>s+g.studentCount,0);const contacts=own.reduce((s,g)=>s+g.studentCount*g.lessonsPerWeek,0);const slotMap=new Map<string,any>();for(const slot of publishedSlots.filter(s=>s.teacherId===teacher.id||Boolean(s.electiveBlockSlotId&&electiveTeachersBySlot.get(s.electiveBlockSlotId)?.has(teacher.id))))slotMap.set(`${slot.dayOfWeek}:${slot.period}`,slot);const slots=[...slotMap.values()];let gaps=0;for(const day of new Set(slots.map(s=>s.dayOfWeek))){const ps=slots.filter(s=>s.dayOfWeek===day).map(s=>s.period).sort((a,b)=>a-b);if(ps.length>1)gaps+=Math.max(0,ps[ps.length-1]-ps[0]+1-ps.length);}return{teacherId:teacher.id,teacherName:teacher.fullName,role:teacher.role,groups:own,groupCount:own.length,weeklyLessons:own.reduce((s,g)=>s+g.lessonsPerWeek,0),uniqueLearners:unique.size,learnerSubjectEnrolments:enrolments,weeklyLearnerContacts:contacts,largestGroup:Math.max(0,...own.map(g=>g.studentCount)),practicalGroups:own.filter(g=>g.practicalHeavy).length,groupsNeedingSplit:own.filter(g=>g.needsSplit).length,publishedTimetableGaps:gaps,continuityAssignments:continuity.filter(c=>c.teacherId===teacher.id).length,activeSubstitutionExposure:substitutions.filter(s=>s.originalTeacherId===teacher.id).length};}).filter(Boolean);
 return{summary:{electiveGroups:groups.length,assignedGroups:groups.filter(g=>!g.staffingGap).length,unassignedGroups:groups.filter(g=>g.staffingGap).length,groupsNeedingSplit:groups.filter(g=>g.needsSplit).length,teachers:teacherRows.length},groups,teachers:teacherRows.sort((a:any,b:any)=>b.weeklyLearnerContacts-a.weeklyLearnerContacts||a.teacherName.localeCompare(b.teacherName))};});}

export async function saveSubjectStaffingRule(user:SessionUser,input:{subjectId:string;recommendedMaxGroupSize?:number|null;practicalMaxGroupSize?:number|null;practicalHeavy:boolean}){return withTenant(user.tenantId,async()=>{const db=tenantDb();const subject=await db.subject.findFirst({where:{id:input.subjectId,archived:false}});if(!subject)throw new Error("Subject not found.");const clean=(n:number|null|undefined)=>n==null?null:Math.max(1,Math.min(500,Math.trunc(n)));return db.subject.update({where:{id:subject.id},data:{recommendedMaxGroupSize:clean(input.recommendedMaxGroupSize),practicalMaxGroupSize:clean(input.practicalMaxGroupSize),practicalHeavy:input.practicalHeavy}});});}
