/** Public demo request intake. A request never creates or logs into a school until NEYO Ops approves it. */
import { NextRequest } from "next/server";
import { z } from "zod";
import { enforceRate, clientIp } from "@/lib/security/rate-limit";
import { ok, handleError } from "@/lib/api/respond";
import { db } from "@/lib/db";
export const dynamic = "force-dynamic";
const schema=z.object({phone:z.string().trim().regex(/^(?:\+254|0)[17]\d{8}$/,"Use a valid Kenyan phone number."),email:z.string().trim().email().max(200),name:z.string().trim().min(2).max(120),schoolName:z.string().trim().max(160).optional(),countySubCounty:z.string().trim().max(160).optional(),contactRole:z.string().trim().max(80).optional(),schoolType:z.enum(["DAY","BOARDING","BOTH","OTHER"]).optional(),approximateLearners:z.number().int().min(1).max(100000).optional(),topProblems:z.string().trim().max(1000).optional(),preferredDemoDate:z.string().optional(),consentToContact:z.literal(true,{errorMap:()=>({message:"Consent to contact is required for the pilot waitlist."})}),campaignSource:z.string().trim().max(120).optional()});
const normalize=(phone:string)=>phone.startsWith("0")?`+254${phone.slice(1)}`:phone;
export async function POST(req:NextRequest){try{enforceRate(`demo-request:${clientIp(req)}`,3,3600);const raw=await req.json();if(typeof raw.phone==="string")raw.phone=raw.phone.replace(/\s+/g,"");const input=schema.parse(raw);const waitlist={phone:normalize(input.phone),fullName:input.name,schoolName:input.schoolName||null,countySubCounty:input.countySubCounty||null,contactRole:input.contactRole||null,schoolType:input.schoolType||null,approximateLearners:input.approximateLearners||null,topProblems:input.topProblems||null,preferredDemoDate:input.preferredDemoDate||null,consentToContact:true,campaignSource:input.campaignSource||"PUBLIC_WEBSITE"};const request=await db.demoRequest.upsert({where:{email:input.email.toLowerCase()},create:{email:input.email.toLowerCase(),...waitlist,status:"PENDING"},update:{...waitlist,status:"PENDING",requestedAt:new Date(),approvedAt:null,approvedBy:null,spawnedTenantId:null,spawnedTenantSlug:null,notes:null}});return ok({requestId:request.id,status:"PENDING",message:"Your request is awaiting NEYO Ops review."},202);}catch(error){return handleError(error);}}
